// Regenerate src/tld-list.ts from the IANA root zone list.
//   node scripts/update-tlds.mjs                      # downloads the IANA list
//   node scripts/update-tlds.mjs tlds-alpha-by-domain.txt
//   node scripts/update-tlds.mjs node_modules/tlds/index.json
// The list only decides whether typed text such as "github.com" is an address;
// it is bundled, never fetched at runtime.
import { readFile, writeFile } from 'node:fs/promises';
import { domainToASCII } from 'node:url';

const source = process.argv[2];
const text = source ? await readFile(source, 'utf8')
  : await (await fetch('https://data.iana.org/TLD/tlds-alpha-by-domain.txt')).text();
const entries = source?.endsWith('.json') ? JSON.parse(text)
  : text.split(/\r?\n/).filter(line => line && !line.startsWith('#'));
const tlds = [...new Set(entries.map(entry => domainToASCII(String(entry).trim().toLowerCase())).filter(Boolean))].sort();
if (tlds.length < 1000 || !tlds.includes('com') || !tlds.includes('xn--fiqs8s')) throw new Error(`Unexpected TLD list (${tlds.length} entries)`);
await writeFile(new URL('../src/tld-list.ts', import.meta.url), `// Generated by scripts/update-tlds.mjs from the IANA root zone list (${tlds.length} entries).
// Internationalized names are stored in their ASCII (punycode) form, as URL hostnames report them.
export const topLevelDomains = ${JSON.stringify(tlds.join(' '))};
`);
console.log(`Wrote ${tlds.length} top-level domains.`);
